//
//  HeaderGenerator.swift
//  DDDKit
//
//  Created by Grady Zhuo on 2025/2/11.
//

package struct HeaderGenerator {
    
    package init() { }
    
    package func render() -> [String]{
        return [
            """
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the event generator plugin.
//

"""
        ]
    }
}
